language: groovy
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - rabahmeradi@gmail.com
      - talos.du13gmail.com
      - julien.wallart@outlook.com

script:
    - ./grailsw test-app -coverage -xml
after_success:
    - ./grailsw coveralls
deploy:
    provider: heroku
    api_key: 2794dcca-5acc-4d83-907d-3899c866e128
    app: astrovisor
