language: groovy
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - rabahmeradi@gmail.com
      - talos.du13gmail.com
      - julien.wallart@outlook.com

script: ./grailsw refresh-dependencies
  && ./grailsw "test-app"
