language: groovy
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - rabahmeradi@gmail.com
      - talos.du13gmail.com
      - julien.wallart@outlook.com

before_script:
  - cd yo
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower karma grunt-cli jshint
  - npm install
  - bower install
  - cd ..

script:
    - ./grailsw test-app -coverage -xml
    - cd yo
    - gulp test
after_success:
    - ./grailsw coveralls
deploy:
    provider: heroku
    api_key: 2794dcca-5acc-4d83-907d-3899c866e128
    app: astrovisor
