language: groovy
jdk:
  - oraclejdk8
branches:
  only:
    - master
script: ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
  && cd test/apps/gson-test
  && ./grailsw refresh-dependencies
  && ./grailsw "test-app functional:"
