language: groovy
jdk:
  - oraclejdk8
branches:
  only:
    - master
script: ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
  && ./grailsw refresh-dependencies
  && ./grailsw "test-app functional:"
